### ISSUE TITLE
Multiple URIs

### ISSUE THREAD

**Issue by pieterjandesmedt** [Raynos/live-reload#1]
Is it possible to make live-reload watch multiple URIs? Something like [onchange](https://github.com/Qard/onchange) is doing would be great!

**Comment by Raynos** [comment]
I havn't worked on this for over 2 years. I dont think this still works.

If it does, then contributions welcome :)

**Comment by thejmazz** [comment]
I was also trying to watch multiple URIs. That didn't work, so I said "ok" and tried to get a MWE, npm run livereload (where livereload: live-reload ./app --port=9001) didn't work. Unless I ran it before http-server. But then http-server wouldn't work. It seems there is a port conflict: both live-reload and http-server give EADDRINUSE errors when ran after the other. 

I'm trying to use npm instead of grunt/gulp, so I'll definitely look into the code at some point and try to fix it myself.

EDIT: just realized I still had <script src="localhost:somePort"></script> in my html file. Maybe that's the problem, maybe not. Too lazy to try it out again lol.
